app: vjepa
nodes: 1
tasks_per_node: 1
tag: physion_pretrain

data:
  dataset_type: VideoDataset
  datasets:
    - /research/d7/spc/yrwang5/V-JEPA/V-JEPA/physion_csv/train_data_mass_vd.csv
  decode_one_clip: true
  batch_size: 4
  num_clips: 1
  num_frames: 16
  tubelet_size: 2
  sampling_rate: 4
  crop_size: 224
  patch_size: 16
  datasets_weights: null

data_aug:
  random_resize_aspect_ratio:
    - 0.75
    - 1.3333
  random_resize_scale:
    - 0.3
    - 1.0
  reprob: 0.0
  auto_augment: false
  motion_shift: false

logging:
  folder: /research/d7/spc/yrwang5/V-JEPA/pretrained_models/
  write_tag: physion_pretrain

loss:
  loss_exp: 1.0
  reg_coeff: 0.0

mask:
  - aspect_ratio:
      - 0.75
      - 0.75
    num_blocks: 8
    spatial_scale:
      - 0.15
      - 0.15
    temporal_scale:
      - 1.0
      - 1.0
  - aspect_ratio:
      - 0.75
      - 1.5
    num_blocks: 2
    spatial_scale:
      - 0.7
      - 0.7
    temporal_scale:
      - 1.0
      - 1.0

meta:
  seed: 42
  eval_freq: 5
  dtype: bfloat16
  use_sdpa: true
  load_checkpoint: false

model:
  model_name: vit_huge
  pred_depth: 12
  pred_embed_dim: 384

optimization:
  epochs: 10
  batch_size: 4
  start_lr: 0.0002
  lr: 0.000625
  final_lr: 1.0e-6
  weight_decay: 0.04
  final_weight_decay: 0.04
  warmup: 5
  ema:
    - 0.998
    - 1.0
  ipe: 150
  clip_grad: 3.0

pretrain:
  folder: /research/d7/spc/yrwang5/V-JEPA/pretrained_models/
  checkpoint: vith16.pth.tar
  checkpoint_key: target_encoder
  model_name: vit_huge
  patch_size: 16
  tubelet_size: 2
  frames_per_clip: 16
  use_sdpa: true
  use_silu: false
  tight_silu: false
  uniform_power: true
